### ISSUE TITLE
Flash AAEON with meta-tegra layer

### ISSUE THREAD

**Issue by renkh** [renkh/final-project-assignment-renkh#2]
Add the NVIDIA meta-tegra layer to meta-aaeon. Add any additional conf files, board support layers, and packages so that the image can be built and ran on the AAEON box. This will be the minimal base image supporting AAEON and meta-tegra. Identify any missing pieces like unsupported ports and missing Jetson SDK components.

Blockers: Issue #4

DoD:

- [x] meta-tegra layer pulled in
- [x] base conf files and board support layers created
- [x] minimal base image builds and runs on the AAEON
- [x] known compatibility issues identified

**Comment by renkh** [comment]
Following issue #4, the AAEON box likely has a hardware variant of **Jetson AGX Xavier development kit** with [T194 SOC](https://en.wikipedia.org/wiki/Tegra). Found a relevant guide called [Yocto Support for NVIDIA Jetson Platforms - Setting up Yocto](https://developer.ridgerun.com/wiki/index.php/Yocto_Support_for_NVIDIA_Jetson_Platforms_-_Setting_up_Yocto) that provides instructions on how to configure and build the meta-tegra layer supporting Xavier T194.

After configuring the repo I ran `bitbake core-image-sato-dev -k`. The Sato image is a reference graphical user interface (GUI) provided by the Yocto Project. It includes various graphical components and applications for testing and development purposes.

The output of the build is in `tmp/deploy/images/jetson-agx-xavier-devkit/`. It contains:
- **core-image-sato-dev-jetson-agx-xavier-devkit.tegraflash.tar.gz** - a compressed tarball containing all of the files, tools, and scripts for flashing the device and/or creating a fully-populated SDcard.
- **tegra194-p2888-0001-p2822-0000-jetson-agx-xavier-devkit.dtb** - a Device Tree Blob (DTB) file for the NVIDIA Jetson AGX Xavier developer kit which matches the DTB file provided by AAEON and covered in the comments for issue #2.

**Comment by renkh** [comment]
Successfully flashed the AAEON box with **jetson-agx-xavier-devkit**.

I followed the flashing guide from the [BOXER-8240AI Manual](https://data-us.aaeon.com/DOWNLOAD/MANUAL/BOXER-8240AI%20Manual%201st%20Ed.pdf) and [Flashing the Jetson Dev Kit](https://github.com/OE4T/meta-tegra/wiki/Flashing-the-Jetson-Dev-Kit#unpacking-the-tegraflash-package) wiki page on meta-tegra. 

The flashing process is as follows:
- unpack the generated `tegraflash` package `core-image-sato-dev-jetson-agx-xavier-devkit.tegraflash.tar.gz`
- Connect the Micro-USB plug on the USB cable to the Recovery Port on the BOXER-8240AI and the other end to an available USB port on the host PC.
- Connect the BOXER-8240AI power supply.
- Power on the system, then press and hold the recovery button. While continuing to hold the recovery button, press and hold the reset button for two seconds before releasing the reset button, then releasing the recovery button.
- When device is in recovery mode, lsusb command on host PC will list a line of "0955:7019 Nvidia Corp"

![Image](https://github.com/renkh/final-project-assignment-renkh/assets/22359270/123dafa3-2a14-4cb0-a681-9dd9c9b7fb60)

- run the `doflash.sh` script to program the AAEON: `$ ./doflash.sh`

Here is some of the output upon successful flash:
```
[  43.7956 ] Writing partition kernel-dtb_b with kernel_tegra194-p2888-0001-p2822-0000.dtb [ 393728 bytes ]
[  43.8178 ] [................................................] 100%
[  43.8283 ] Writing partition esp with esp.img [ 67108864 bytes ]
[  43.8373 ] [................................................] 100%
[  46.7091 ] tegradevflash_v2 --write secondary_gpt_backup gpt_secondary_0_3.bin
[  46.7111 ] Bootloader version 01.00.0000
[  46.7379 ] Writing partition secondary_gpt_backup with gpt_secondary_0_3.bin [ 16896 bytes ]
[  46.7383 ] [................................................] 100%
[  46.7505 ] tegradevflash_v2 --write BCT br_bct_BR.bct
[  46.7523 ] Bootloader version 01.00.0000
[  46.7824 ] Writing partition BCT with br_bct_BR.bct [ 2888 bytes ]
[  46.7828 ] [................................................] 100%
[  46.9206 ] tegradevflash_v2 --write BCT-boot-chain_backup bct_backup.img
[  46.9224 ] Bootloader version 01.00.0000
[  46.9542 ] Writing partition BCT-boot-chain_backup with bct_backup.img [ 32768 bytes ]
[  46.9546 ] [................................................] 100%
[  46.9670 ] tegradevflash_v2 --write MB1_BCT mb1_cold_boot_bct_MB1_sigheader.bct.encrypt
[  46.9687 ] Bootloader version 01.00.0000
[  46.9984 ] Writing partition MB1_BCT with mb1_cold_boot_bct_MB1_sigheader.bct.encrypt [ 31024 bytes ]
[  46.9997 ] [................................................] 100%
[  47.0263 ] tegradevflash_v2 --write MB1_BCT_b mb1_cold_boot_bct_MB1_sigheader.bct.encrypt
[  47.0321 ] Bootloader version 01.00.0000
[  47.0626 ] Writing partition MB1_BCT_b with mb1_cold_boot_bct_MB1_sigheader.bct.encrypt [ 31024 bytes ]
[  47.0632 ] [................................................] 100%
[  47.1687 ] tegradevflash_v2 --write MEM_BCT mem_coldboot_sigheader.bct.encrypt
[  47.1722 ] Bootloader version 01.00.0000
[  47.2029 ] Writing partition MEM_BCT with mem_coldboot_sigheader.bct.encrypt [ 198656 bytes ]
[  47.2037 ] [................................................] 100%
[  47.3034 ] tegradevflash_v2 --write MEM_BCT_b mem_coldboot_sigheader.bct.encrypt
[  47.3056 ] Bootloader version 01.00.0000
[  47.3345 ] Writing partition MEM_BCT_b with mem_coldboot_sigheader.bct.encrypt [ 198656 bytes ]
[  47.3354 ] [................................................] 100%
[  47.3531 ] Flashing completed

[  47.3533 ] Coldbooting the device
[  47.3561 ] tegrarcm_v2 --ismb2
[  47.4375 ] tegradevflash_v2 --reboot coldboot
[  47.4431 ] Bootloader version 01.00.0000
```

**Comment by renkh** [comment]
Because this is a GUI image, I was able to plug the DP cable from the AAEON and to the monitor and get to the terminal window. Through there I ran `ifconfig` and saw 2 network devices `eth0` and `eth1`, I then assigned an IP address to `eth0` and was able to ssh into the AAEON box via an ethernet cable.

The ssh command I ran is `ssh root@192.168.88.5` no password.

**Comment by renkh** [comment]
Known issues:
- networking is not set up on first boot
- 2 of the 4 ethernet ports are not up

Things that work:
- USB 2.0 and 3.0
- DisplayPort
- 2/4 ethernet ports

Ports I haven't tried:
- CAN
- COM
- HDMI
- SDcard

Have not checked that the necessary libraries, drivers, and packages are properly set up. Running `nvcc --version` and `nvidia-smi` did not return anything. Will need to verify that in the upcoming tickets.
